### ISSUE TITLE
EPMC Article title lookup reported to not work

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#81]
Example job https://compliance.cottagelabs.com/#hwDyzA7ypm9onu6PQ

> I think I can confirm that the title lookups are NOT working, for example the article “Non-specific Mechanisms in Orthodox and CAM management of low back pain (MOCAM). Theoretical Framework and Protocol for a Prospective Cohort Study” is found when I search for it using its title either as a free text search or using the syntax which the tool should be using: TITLE:"Non-specific Mechanisms in Orthodox and CAM management of low back pain (MOCAM). Theoretical Framework and Protocol for a Prospective Cohort Study". This is not the only title from that spreadsheet which I can find (as the only result returned) via Europe PMC using the title search.

I can get more example titles if needed.

**Comment by markmacgillivray** [comment]
Fixed error in regex title cleaner

**Comment by emanuil-tolev** [comment]
@markmacgillivray The "Non-specific Mechanisms in Orthodox and CAM management of low back pain (MOCAM). Theoretical Framework and Protocol for a Prospective Cohort Study" article's still not working for me, see attached CSV.

[article_lookup_test.csv.zip](https://github.com/CottageLabs/LanternPM/files/399543/article_lookup_test.csv.zip)

You know what the really weird thing is though? I connect to the machine managing the live API deployment, I do `cd live/api && meteor shell` and then

```
> proc = {title: "Non-specific Mechanisms in Orthodox and CAM management of low back pain (MOCAM). Theoretical Framework and Protocol for a Prospective Cohort Study"}
> lantern_results.findByIdentifier(proc)
```

and this returns an entirely reasonable result! The article has been identified, so have some of its identifiers, and there is even a licence result.

However, the results file I get from compliance.cottagelabs.com just has "unknown" all across. I pulled the CL API master locally, made sure my static files (wellcome.js and .css) that use the API are up to date, ran the file, and got unknowns everywhere - same as live.

**Comment by emanuil-tolev** [comment]
Also, locally I wipe all collections before running anything

```
curl -XDELETE http://localhost:3002/api/mongo/remove/lantern_meta &&
curl -XDELETE http://localhost:3002/api/mongo/remove/academic_licence &&
curl -XDELETE http://localhost:3002/api/mongo/remove/lantern_results &&
curl -XDELETE http://localhost:3002/api/mongo/remove/lantern_jobs &&
curl -XDELETE http://localhost:3002/api/mongo/remove/lantern_processes &&
curl -XDELETE http://localhost:3002/api/mongo/remove/academic_licence ; echo
```

**Comment by emanuil-tolev** [comment]
I'm about to test with different article titles. The reason I'd like to get this one to work is that Cecy will likely use it to test.

**Comment by emanuil-tolev** [comment]
I called the column in the CSV `Article Title`, not `Article title` (mine had a capital T). Oops. Works fine :+1: .

**Comment by markmacgillivray** [comment]
So it is OK, or still a problem?

**Comment by markmacgillivray** [comment]
So what about it is currently not working? I did a test that worked, in
that found the article epmc using just title, which is why I closed issue.
Is it the column header?

**Comment by markmacgillivray** [comment]
Our comments seem to have overlapped. Odd. So is this issue open or closed? Shows as closed now. Do you want me to look into it again or not? I'd guess that it is finding it the first time it goes into the system, but not matching the result out after for later queries for the same title. I can check this, if you let me know this needs to be reopened and looked at @emanuil-tolev

**Comment by emanuil-tolev** [comment]
No, no, it's closed. Turned out my column was named wrong, it was Article Title, but it needs a lowercase "t" to work - Article title.

We could consider warning users if nothing but capitalisation differs in a column name (at least for the 4 identifier columns). Besides me, I'm pretty sure our Wellcome friends have gotten this column name wrong a few times.

That's a different feature however. Article lookups themselves are fixed, I'll just have to watch out for that pesky column name.

**Comment by markmacgillivray** [comment]
OK can add a check for casing of that column name anyway, won't be hard.
